### ISSUE TITLE
Edit or Remove Calendar (BE)

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#100]
Description: "As a user, I want to be able to edit or remove my calendars."

Story Points: 8

Priority: Low risk, High value

Acceptance Test: -

Tasks:
- Create the event class
- Create the calendar class
- Create the sql requests
- Create the methods to edit fields in event and calendar classes

**Comment by eCom0327** [comment]
LOW risk, HIGH value

**Comment by g-harel** [comment]
L risk H value

**Comment by faisalhabibgit** [comment]
Done
