### ISSUE TITLE
Lists of Events in Interface

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#101]
Description: "As a user, I want to be able to see my lists of events in a GUI that represents a calendar."

Story Points: 40

Priority: -

Acceptance Test: -

**Comment by eCom0327** [comment]
HIGH risk, HIGH value

**Comment by g-harel** [comment]
H risk H value

**Comment by g-harel** [comment]
Priority 1

**Comment by g-harel** [comment]
### Tasks
- draw weekly schedule to container
- draw monthly schedule to container
- find current date and time in local timezone
- number the days in container
- button to switch from month to week
- draw time intervals with variable max/min
- highlight current day
- line for current time
- fetch all events in day range
- place events into the correct days and at the proportional correct times
- scale events height to duration (both interfaces)
- color events according to calendar
- only show events that pass a filter
- allow arbitrary filters to events being shown
