### ISSUE TITLE
Edit Calendar GUI

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#103]
Description: "As a user, I want to be able to edit my calendars through a GUI."

Story Points: 8

Priority: -

Acceptance Test: -

**Comment by eCom0327** [comment]
LOW risk, HIGH value

**Comment by g-harel** [comment]
H risk H value

**Comment by ekowpo** [comment]
H risk H value

**Comment by jaslatendresse** [comment]
Tasks

- [ ] - Create reusable modal window element. 
- [ ] - Implement create new calendar 
    - [ ] - Calendar title field
    - [ ] - Calendar color picker 
    - [ ] - Server response 
- [ ] - Implement edit event 
    - [ ] - New event title 
    - [ ] - New event time 
    - [ ] - New event description
    - [ ] - Server response --> student/admin
- [ ] - Implement add event
    - [ ] - Event title
    - [ ] - Event time 
    - [ ] - Event description
    - [ ] - Server response --> student/admin
