### ISSUE TITLE
GUI Login

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#104]
Description: "As a user, I want to be able to start a session with the server through a GUI."

Story Points: 5

Priority: -

Acceptance Test: -

**Comment by eCom0327** [comment]
LOW risk, HIGH value

**Comment by g-harel** [comment]
H risk H value

**Comment by RanjuShetty** [comment]
I think it should be a high risk and high value

**Comment by jaslatendresse** [comment]
Tasks

- Create email field for user input
- Create password field for user input
- Create regex for email format
- Create GUI if email format is not respected
- Create regex for password format
- Create GUI if password format is not respected 
- Create login button
