### ISSUE TITLE
Access Calendar

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#105]
Description: "As a user, I want to be able to access a calendar provided I have a link and a password for it."

Story Points: 8

Priority: High risk, High value

Acceptance Test: -

Tasks:
- Create the sql request to query the database for the link and check the password
- Create the sql request to add a password to a user
- Update the database to reflect access to a calendar

**Comment by eCom0327** [comment]
LOW risk, HIGH value

**Comment by g-harel** [comment]
H risk H value

**Comment by RanjuShetty** [comment]
Both entail a high risk and value as it affects the functionality of calendar to users.
