### ISSUE TITLE
Frontend tech stack

### ISSUE THREAD

**Issue by g-harel** [SOEN341-Group1/KoalaCal#112]
Hello everyone, 

So from what I understood, we have decided as a team to use Angular as our front-end framework for this project. I have therefore gone ahead and added a boilerplate angular setup to our front-end folder in order to get the ball rolling. However, there are a few issues I think it is worth bringing up.

First off, I want to make sure that everyone is aware that we are currently using Angular 2. This is important since versions 1 and 2 are incompatible and have significant differences. The decision to go with 2 is still up for debate, but I think it would be the most forward-thinking approach.

Secondly, the setup that I have put in the repo is one I felt would be the most accessible to everyone since it uses a classic html/css/js "layout". The problem is that it lends itself horribly to any kind of build system/automatic testing. Angular 2 is written in typescript, which is a superset of the JavaScript language which adds extra syntax for things like variable types. This can be leveraged by code editors to provide proper error checking similar to what you would get in eclipse/netbeans. More traditional Angular 2 setups use "auto-compilers" to bundle all the code and build the app from all the separate components. This means we could avoid using tons of `<script>` tags and instead have something that looks a lot more like java's `import`. I would 2000% prefer this kind of project setup, but it would make the learning curve steeper for people that are not used to this type of tooling.

I don't want to impose my decisions so I have opened this issue for us to discuss our approach.

@NepheriusIsTaken @RemusCM @ekowpo @jaslatendresse @eCom0327 @RanjuShetty @faisalhabibgit

**Comment by jaslatendresse** [comment]
I think for this kind of project, Angular would be a good framework even if i'm not too familiar with it, i read about it. I don't know the difference between Angular 1 and Angular 2 so i leave that into the hands of those who do know. However, since we have not started to code yet, we need something that everyone will be comfortable with and that's quick to learn.

**Comment by ekowpo** [comment]
Angular 1 is far easier than 2. if you are okay with typescript then angular 2 will be fine. angular 1 works just like adding addition attribute to a tag/creating new ones. I am not that good but I helped a friend with his interview project.

**Comment by g-harel** [comment]
@ekowpo I like that idea, it would be simpler for everyone.
I will switch the current contents of the frontend folder after class.

**Comment by faisalhabibgit** [comment]
Since I know a bit of Angualar it might be hard for me to answer this question, beside this I am open to learn Angular 2 if the whole team is going with that. I am fine both ways
