### ISSUE TITLE
Scheme Review

### ISSUE THREAD

**Issue by ekowpo** [SOEN341-Group1/KoalaCal#114]
![scheme](https://cloud.githubusercontent.com/assets/15113067/22995467/05186238-f399-11e6-9018-1fac52d56099.PNG)

**Comment by g-harel** [comment]
I'm not a fan of the studentid field in the user table.
Is this implying we would store user passwords in plaintext ?
What is the purpose of the calendarusers table ?

**Comment by ekowpo** [comment]
This saves the user once the user enters the calendar access code. to prevent them from entering the password each time they login.

**Comment by ekowpo** [comment]
No, the password will not be in plain Text. the MD5 encryption Text will be saved in the password field. Text allows long strings.

**Comment by g-harel** [comment]
MD5 is not good enough anymore, it can be decrypted quite easily. SHA256 is the current standard

**Comment by ekowpo** [comment]
No problem, at the end of the day it will be text which the field can hold. That is what am putting across not the encryption algorithm but thanks for the heads up and suggestion. we will use SHA256

**Comment by g-harel** [comment]
I think it would be great to add a calendar color field so that users can change the color of their individual calendars independantly

**Comment by ekowpo** [comment]
Calendar color can't be kept in the calendar table due to the fact that we will have different calendars that can be merged into a single view. Which color do you use then? In cases like this, there is a separate table containing user theme, This keeps configuration pertaining to an individual like the color background, image, font family, font size and etc.

**Comment by g-harel** [comment]
Calendars can have different colors and be in the same display, this is critical

**Comment by ekowpo** [comment]
if you are viewing them as individual entities yes.

**Comment by ekowpo** [comment]
if soen 341 is red, and soen 460 is blue if you merge the calendars what color will it be.? I believe we have one view where we can filter which calendar we wish to see or merge them.

**Comment by g-harel** [comment]
Different color boxes for each calendar, trust me I will need color in the interface

**Comment by ekowpo** [comment]
so in creating a calendar you select a color to match

**Comment by g-harel** [comment]
Yes, random color is generated, but it can be changed on creation or later

**Comment by ekowpo** [comment]
![Uploading schemeupdate.PNG…]()

**Comment by ekowpo** [comment]
![schemeupdate](https://cloud.githubusercontent.com/assets/15113067/23071735/4ee36bdc-f4fd-11e6-92d6-e1c5bd92e061.PNG)
