### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by NepheriusIsTaken** [SOEN341-Group1/KoalaCal#167]
@faisalhabibgit 
@ekowpo 
From Conversation in slack:

btanguay [12:44 PM] 
I've worked on integration testing for the backend today. I'm confident I'll be able to finish writing testing methods for all the things present in DBCON before the end of tomorrow.

[12:44]  
I've already finished all that is related to the events.

fais [12:44 PM] 
Cool

g-harel [12:44 PM] 
yay gj

fais [12:44 PM] 
Great work

btanguay [12:47 PM] 
Do we want to do unit testing as well?

[12:48]  
For the backend, it looks kind of stupid since there is no "business logic". It's all queries to the db and setters/getters

g-harel [12:48 PM] 
I'm not sure that what we test matters too much

[12:49]  
as long as it's there

fais [12:55 PM] 
@btanguay  you are right

[12:55]  
But we will still beef

[12:55]  
Need

[12:55]  
I know it sound stupid

btanguay [12:56 PM] 
okay

[12:56]  
I'll create some unit tests on the beans as well

[12:56]  
I may not do all beans since it's going to be very tedius

[12:56]  
tedious

[12:58]  
Btw fais, is it normal that my dependency for javax.mail can't be correctly imported in SendEmail.java?

ekowpo [1:03 PM] 
You don't test beans

btanguay [1:04 PM] 
What do you want to unit test then?

ekowpo [1:04 PM] 
Creating a object and passing values to it

[1:04]  
Create calendar

[1:04]  
Add events

btanguay [1:04 PM] 
Those are integration tests

ekowpo [1:04 PM] 
No

fais [1:05 PM] 
Yes @btanguay it's completely normal

[1:05]  
Comment that for now

[1:05]  
I'll show you how to fix that when we meet

ekowpo [1:05 PM] 
You test the function /method

fais [1:05 PM] 
We need a library for that

[1:05]  
Don't test the beans

[1:05]  
Test the logic lol

[1:05]  
There isn't business logic but still

btanguay [1:05 PM] 
Testing the beans makes no sense to me anyway so I'm glad we don't have to do it.

fais [1:05 PM] 
We need unit tests

[1:05]  
So what you can do is

btanguay [1:06 PM] 
But for the rest, if we don't mock the database, then whatever we do is by definition an integration test since it integrates more then 1 service together

fais [1:06 PM] 
Create a test class and call methods and then check if the values are stored in the database by calling other methods

ekowpo [1:06 PM] 
Example create a calendar object

fais [1:06 PM] 
That's all we can test at this point

[1:06]  
Oh yes

[1:06]  
Let's mock that's a great idea

ekowpo [1:06 PM] 
Yes

fais [1:07 PM] 
I'll write some tests tonight

[1:07]  
You can look at those and then continue after words if you want

[1:07]  
I am at work now I can't do it now

btanguay [1:08 PM] 
We should do the opposite. I'll push what I've done ASAP. You can check it and see if you want me to continue going in the same direction. We don't want to work on the same test twice.

fais [1:09 PM] 
Awesome !

[1:09]  
I'll check it now

[1:09]  
You can push it now :)

btanguay [1:12 PM] 
@fais  You can check, I've pushed the branch BE-JUnit-Testing

btanguay [1:20 PM] 
Hmmm, the test fails to run though. I'll need to debug it some.

fais [1:21 PM] 
I was about to ask the same questions

[1:21]  
btw great work man

btanguay [1:22 PM] 
It seems like it's a question of the build path pointing at the wrong place

g-harel [1:22 PM] 
hey guys, this would be a great conversation to have on a github issue

**Comment by NepheriusIsTaken** [comment]
Error atm: Native library for Attach API not available in this JRE

Possible solution: http://stackoverflow.com/questions/11961571/jmockit-native-library-for-attach-api-not-available-in-this-jre-error

**Comment by faisalhabibgit** [comment]
@NepheriusIsTaken I really liked your approach may be you can take out the event table creation since the schema will be created once and for all

**Comment by faisalhabibgit** [comment]
the rest it's a great way to test such code I will follow you on this

**Comment by NepheriusIsTaken** [comment]
The idea is that the table is created and destroyed in memory just for the test.

**Comment by NepheriusIsTaken** [comment]
That's why I need to create the table, even though the schema already exists.

**Comment by faisalhabibgit** [comment]
well yes if it stays in the memory and is destroyed afterwards it's completely fine to do it this way
you can work on making the test app and then we are all set I will follow your approach as well

**Comment by faisalhabibgit** [comment]
@NepheriusIsTaken  keep up with the good work :+1:

**Comment by NepheriusIsTaken** [comment]
I fixed the basics problems (eclipse needs to point towards the most recent JDK and there was one dependency missing in maven) and the test class runs without crashing. Problem is the configuration fails before the actual test can be run. It seems that the thing ends its execution after it reaches the line:
Deencapsulation.setField(DBCON.class, "connection", connection);

I am not sure where the problem is coming from. Maybe the configuration code is faulty. Maybe mySQL itself  on my computer is badly configured. Can you guys try to run the code to see if you get the same thing?

Stacktrace:

[main] INFO ch.vorburger.mariadb4j.Util - Created directory: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\libs
[main] INFO ch.vorburger.mariadb4j.Util - Created directory: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537
[main] INFO ch.vorburger.mariadb4j.Util - Unpacked 40 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.1.20/win32/** to C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base
[main] INFO ch.vorburger.mariadb4j.DB - Installing a new embedded database to: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base
[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: Running bootstrap
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: 2017-03-22 14:04:36 15948 [Note] C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 7280 ...
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: Removing default user
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: Creating my.ini file
[Exec Default Executor] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: Creation of the database was successfull
[Exec Default Executor] INFO ch.vorburger.exec.ManagedProcess - Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base) just exited, with value 0
[main] INFO ch.vorburger.mariadb4j.DB - Installation complete.
[main] INFO ch.vorburger.mariadb4j.DB - Starting up the database...
[main] INFO ch.vorburger.mariadb4j.DB - mysqld executable: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe
[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[main] INFO ch.vorburger.exec.ManagedProcess - Thread will wait for "mysqld.exe: ready for connections." to appear in Console output of process Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base) for max. 30000ms
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 14152 ...
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Using mutexes to ref count buffer pool pages
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: The InnoDB memory heap is disabled
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Compressed tables use zlib 1.2.3
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Using generic crc32 instructions
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Initializing buffer pool, size = 128.0M
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Completed initialization of buffer pool
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Setting log file .\ib_logfile101 size to 48 MB
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:40 9364 [Note] InnoDB: Setting log file .\ib_logfile1 size to 48 MB
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] InnoDB: Renaming log file .\ib_logfile101 to .\ib_logfile0
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Warning] InnoDB: New log files created, LSN=1622818
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] InnoDB: Highest supported file format is Barracuda.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] InnoDB: 128 rollback segment(s) are active.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] InnoDB: Waiting for purge to start
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.34-79.1 started; log sequence number 1623052
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 21568 [Note] InnoDB: Dumping buffer pool(s) not yet started
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] Plugin 'FEEDBACK' is disabled.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] Server socket created on IP: '::'.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2017-03-22 14:04:41 9364 [Note] C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe: ready for connections.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: Version: '10.1.20-MariaDB'  socket: ''  port: 53537  mariadb.org binary distribution
[main] INFO ch.vorburger.mariadb4j.DB - Database startup complete.
[main] INFO ch.vorburger.mariadb4j.DB - Running a command: create database if not exists `test`;
[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[Exec Default Executor] INFO ch.vorburger.exec.ManagedProcess - Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base) just exited, with value 0
[main] INFO ch.vorburger.mariadb4j.DB - Successfully ran the command: create database if not exists `test`;
[Shutdown Hook Deletion Thread for Temporary DB C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] INFO ch.vorburger.mariadb4j.DB - cleanupOnExit() ShutdownHook now stopping database
[Shutdown Hook Deletion Thread for Temporary DB C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] INFO ch.vorburger.exec.ManagedProcess - Successfully destroyed Program [C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base, --datadir=C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537, --port=53537] (in working directory C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base)
[Shutdown Hook Deletion Thread for Temporary DB C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] INFO ch.vorburger.mariadb4j.DB - Database stopped.
[Shutdown Hook Deletion Thread for Temporary DB C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] INFO ch.vorburger.mariadb4j.DB - cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537
[Shutdown Hook Deletion Thread for Temporary DB C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\data\53537] INFO ch.vorburger.mariadb4j.DB - cleanupOnExit() ShutdownHook quietly deleting temporary DB base directory: C:\Users\Benjamin\AppData\Local\Temp\MariaDB4j\base

**Comment by NepheriusIsTaken** [comment]
@faisalhabibgit 
@ekowpo 

I created another integration test, this time fr the DBCON methods that interact with the calendar table. I need you guys to try and run the JUnit test code for the events. I want to know whether the thing fails because of a faulty configuration of mySQL on my computer or because of something that affects all systems. If you get a trace different from the one I posted above, please post it here so that I can troubleshoot it.

DBCON methods that still need to be tested:

DBCON.addEventInCalendar(id, event);				// Does it depend on event table? Check code.
DBCON.removeSharedCalendar(id, email);				
DBCON.shareCalendar(id, email);						
DBCON.updateDetails(user);							
DBCON.ChangePassword(credentials);					

I have a math exam tomorrow. I'll write one or two more test classes tomorrow night. Should be fairly quick since there are very few methods left to test.

**Comment by NepheriusIsTaken** [comment]
After much work, the tests are finally operational and online. For at least one week, the tests didn't work on the repository because of a case sensitivity issue. Closing the thread since the problem is finally resolved.
