### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by eCom0327** [SOEN341-Group1/KoalaCal#28]
Issue to write down languages you know and don't know to help split up tasks later on.

**Comment by eCom0327** [comment]
Languages I know: html, CSS, Javascript
Languages I sort of know: php
Languages I don't know: mySQL

So I'm better with front end than back end.

**Comment by g-harel** [comment]
#### Tech I'm comfortable with:
- HTML/CSS
- Vanilla JavaScript + Frameworks
- NodeJS/Express server
- Java
#### Somewhat comfortable: 
- MySQL
- php

I have a preference towards stuff I'm comfortable with, but I'm open to trying other things if you guys want to.

**Comment by NepheriusIsTaken** [comment]
To follow the same format:
Languages I know: html, CSS, Javascript, Java
Language I sort of know: php, mySQL

Even if it means a little more work and we need to learn new things, I would prefer it if we could program the server side in JavaScript or Java instead of PHP. PHP is a language that doesn't have the best reputation in the industry.

**Comment by faisalhabibgit** [comment]
FrontEnd : HTML/Css
Scripting Languages : JavaScript, PHP
BackEnd : Java
DB : mySQL (Down for any other DB you guys choose)
API : Know REST more than SOAP (always down to learn SOAP if needed)

**Comment by RanjuShetty** [comment]
FrontEnd -> HTML, JavaScript                                                                                                                                              
Backend -> MySQL
I am open to learn  new programming language.

**Comment by jaslatendresse** [comment]
**Languages I know**

- HTML5

- CSS

- Javascript

- Java (Although this would apply more to back-end and I am more comfortable with front-end) 

**Languages I somewhat know**

- PHP

- Python

**Languages I don't know**

- MySQL

- Different frameworks like Node, Django, React...

**Comment by RemusCM** [comment]
I'm also more comfortable with front-end web development using HTML/CSS/Javascript. 
I'm rusty with PHP, so I would need to review it. I would not mind learning any other language.

**Comment by ekowpo** [comment]
I am comfortable with the following:

**Languages:**
Java,
C#,
Asp.net
HTML,
Angular,
CSS3,
PHP and Nusoap(PHP framework for creating SOAP) 

**Database:**
Mysql,
Ms-SQL
