### ISSUE TITLE
What is the name of our project?

### ISSUE THREAD

**Issue by g-harel** [SOEN341-Group1/KoalaCal#34]
Now that we have decided the direction, does anyone have any ideas for good name?

I can make a logo/favicon for us once that gets decided.

**Comment by NepheriusIsTaken** [comment]
Here are a few ideas. I wouldn't choose any of them for a commercial app, but for a school project, I think we can choose whatever.

SchoolTracker
DateKeeper
iCalendar
Concordia's Agenda
Make agenda great again

**Comment by g-harel** [comment]
I find those a bit boring ☹️

**Comment by jaslatendresse** [comment]
ConcoCal...ConUCal...

**Comment by g-harel** [comment]
But then it's explicitly for concordia

**Comment by RemusCM** [comment]
While I was looking at some video on Invision, the person developped a prototype named NightOwl, which had as a logo a cartoonish owl. 
I guess I came up with these two ideas...
PandAgenda 
Salamander Calendar
I could think of more ideas if you want to with this type of reasoning. Not only does this help with the creation of the logo, but this could also inspire with the themes/ design of the website.
Let me know what you think.

**Comment by g-harel** [comment]
I like those two.

**Comment by jaslatendresse** [comment]
i like pandagenda

**Comment by eCom0327** [comment]
I prefer pandagenda over salamander calendar since it's shorter. How about Koalendar?

**Comment by g-harel** [comment]
I like that one too, but it sounds a bit like coal and we're a zero emissions project

**Comment by jaslatendresse** [comment]
While i like pandagenda (or pandalendar) and think it's great to give a theme to our app, it would be good to have a serious, neat name. Something like "PLANify" (I just googled it and it already exists) but something that doesn't necessarily involves the word "calendar" or "agenda" but maybe the features of the app (planning, sharing, merging, organizing...)

**Comment by g-harel** [comment]
How about "Koala Cal"?

For some reason I like the koala mascot.

**Comment by jaslatendresse** [comment]
I like that! But panda would be easier to add a theme to the project. Also, since a panda is typically black and white together, it could mean "merging" stuff together like our project is supposed to do (i know i know that's kind of far) but i don't mind the random name either!

**Comment by eCom0327** [comment]
Koala Cal is better than Koalendar (easier to pronounce). A panda theme will be easier to implement colour wise than a koala one, but might be too stark for the colour contrast.

**Comment by faisalhabibgit** [comment]
I think we can drop our Choices to few and then vote for the name of our project out of those choices. Will be fair and easy

**Comment by ekowpo** [comment]
Yup

**Comment by jaslatendresse** [comment]
I agree

**Comment by g-harel** [comment]
Ok so I will make a list here with all the current candidates and we can vote later. Anyone can update my comment if one of their picks isn't here.

- Koala Cal
- Pandagenda
- Salamander Calendar

**Comment by faisalhabibgit** [comment]
Awesome !
I will just Vote when its time. Don't really have any name in mind.

**Comment by NepheriusIsTaken** [comment]
I created a strawpoll to vote on Koala Cal, Pandagenda and Salamender Calendar options. You can choose more than 1 option.

http://www.strawpoll.me/12256218

**Comment by NepheriusIsTaken** [comment]
3-3 Koala Cal / Pandagenda

Need two more votes. Hopefully, it doesn't end at 4-4...

**Comment by faisalhabibgit** [comment]
I hope not. If it does we flip a coin on Friday between our two little teams inside a team 😆
