### ISSUE TITLE
Integrate Travic CI with our Repo

### ISSUE THREAD

**Issue by faisalhabibgit** [SOEN341-Group1/KoalaCal#36]

**Comment by faisalhabibgit** [comment]
I will wait until I know which language are we going to use for the backend. Since I will setup configuration file based on the  language we use for BE in order for Travis to work as Expected

**Comment by faisalhabibgit** [comment]
If you guys see Travis failing for now it's completely fine. Since I didn't configure it yet. So after a pull request you guys can manually merge into Sprint(X) in case Travis blocks the merge. 
Also I would need to know the language that we are going to use for backend so I can put it in .travis.yml

**Comment by g-harel** [comment]
I don't think we've made a decision about that yet, maybe we can talk about it on friday

**Comment by faisalhabibgit** [comment]
Cool thanks

**Comment by ekowpo** [comment]
So Friday then
