### ISSUE TITLE
KoalaCal logo

### ISSUE THREAD

**Issue by g-harel** [SOEN341-Group1/KoalaCal#77]

**Comment by NepheriusIsTaken** [comment]
[Perhaps something like this but in vector form?
](http://images.onionstatic.com/clickhole/3081/1/original/960.jpg)

**Comment by RemusCM** [comment]
[I was thinking more of this in a cartoonish style](https://s-media-cache-ak0.pinimg.com/736x/66/b9/45/66b945f858e618e5a4f1f0b2b64202ff.jpg)

It could show how relieved you are after using our application and seeing how easy it is to use.

**Comment by g-harel** [comment]
I like that expression!

Are we going for a mascot or a symbol then. Sounds like you guys like the mascots.

**Comment by g-harel** [comment]
![](https://i.gyazo.com/181a7b3948cebbe72058dc5ee976351e.png)
what are you guys' thoughts on this ?
If anyone has any font suggestions, I was thinking some kind of bold handwritten one but I couldn't pick.

**Comment by jaslatendresse** [comment]
@g-harel i like it. Minimalistic, a bit cartoonish but not too much. It's nice

**Comment by RemusCM** [comment]
It's great. I like it.

**Comment by faisalhabibgit** [comment]
@g-harel  I like it too. It's a good one

**Comment by RanjuShetty** [comment]
@g-harel This looks good and It best suits to our concept.

**Comment by eCom0327** [comment]
@g-harel Great logo.
