### ISSUE TITLE
Design the database

### ISSUE THREAD

**Issue by NepheriusIsTaken** [SOEN341-Group1/KoalaCal#79]

**Comment by g-harel** [comment]
I will start with a first draft idea. I've separated this into to categories (users and calendars) each with an idea for the api and the database that would support it. I am not the most comfortable with MySQL, so I am not sure how feasible it is to have sub tables (maybe can be done by separate "calendar events" and "calendar changes" tables.

~~~~
* restricted access by user
^ restricted access by key

- users
    - api
        - create
        - login
        - logout*
        - get settings*
        - edit settings*
        - add calendar*
        - remove calendar*
        - delete*
    - database
        - id #
        - username ""
        - email ""
        - date created # (for password hash)
        - password hash ""
        - authenticated calendars
            - calendar id #
            - calendar join date #
            - calendar key ""
- calendars
    - api
        - create*
        - delete*
        - get events^
        - submit change^ (if not admin, add to calendar changes table)
    - database
        - id #
        - admin id #
        - key ""
        - calendar events
            - id #
            - date #
            - duration #
            - description ""
        - calendar changes
            - event id #
            - issuer id #
            - change type "" (ADD, REMOVE, EDIT)
            - change data ""
~~~~

**Comment by jaslatendresse** [comment]
Although i have no knowledge of database whatsoever, i see where you're going and it seems to make sense. This design also gives us an idea on what we need to have on the user interface depending on if it's a student or admin using it.

**Comment by NepheriusIsTaken** [comment]
Let me try my hand at this. I'll just do the database part here:

Users table:
- User ID #
- UserName ""
- Email ""
- Password "" --> I'm taking the naive approach here. Don't know what we need to make the passwords secured. Don't know if we care enough in this project to make the passwords secured.
- Calendar1 ID #
- Calendar2 ID #
- Calendar3 ID #
- Calendar4 ID #
- Calendar5 ID #
- Calendar6 ID #
- Calendar7 ID #
- Calendar8 ID #
- Calendar9 ID #
- Calendar10 ID #
(We manage a maximum of 10 calendars per users)

Calendar table:
- Calendar ID #
- Creator ID # (it's a user ID)
- Creation date ""

Event table:
- Event ID #
- Calendar ID #
- Creator ID #
- Accepted by admin "" (boolean)
- Title ""
- Time ""
- Date ""
- Description ""
- File ""
- Group # (so we can color code events)

Color code table
- User ID #
- Color ""
- Event group #

**Comment by eCom0327** [comment]
@g-harel  Why is there a colour code table? Wouldn't it be simpler to integrate the info in that table into one of the other tables?

**Comment by RanjuShetty** [comment]
Rather than color table as a separate if it is combined with the calender table,it will ensure normalization and also the values will be cohesive leading to a low coupled code and database queries.

**Comment by g-harel** [comment]
@eCom0327 The color table is not in my spec
